
services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/QuizaPP
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo-data:
