services:
  - type: static_site
    name: mon-app-frontend
    rootDir: client
    buildCommand: npm install && npm run build
    publishDir: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://mon-app-backend.onrender.com

  - type: web
    name: mon-app-backend
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://mon-app-frontend.onrender.com
